from openai import OpenAI
import time, subprocess
from reqs import open_api_key as key
from IDs.OnshapeGPTID import ID

#Reference for training and calling the assistant https://towardsdatascience.com/how-to-build-an-ai-assistant-with-openai-python-8b3b5a636f69

f = open('TextToCAD.py','w')

def wait_for_assistant(thread, run):
    """
        Function to periodically check run status of AI assistant and print run time
    """
    # wait for assistant process prompt
    t0 = time.time()
    while run.status != 'completed':

        # retreive status of run (this might take a few seconds or more)
        run = client.beta.threads.runs.retrieve(
          thread_id=thread.id,
          run_id=run.id
        )
        # wait 0.5 seconds
        time.sleep(0.1)
    dt = time.time() - t0
    print("Done! Elapsed time: " + str(round(dt,2)) + " seconds")
    
    return run

client = OpenAI(api_key=key)

thread = client.beta.threads.create()

user_input = input("Ask OnshapeGPT to create something!\nPrompt:  ")
print('Running...')
message = client.beta.threads.messages.create(thread_id=thread.id,role='user',content=user_input)
run = client.beta.threads.runs.create(thread_id=thread.id,assistant_id=ID)
run = wait_for_assistant(thread, run)
messages = client.beta.threads.messages.list(thread_id=thread.id)
generatedresponse = messages.data[0].content[0].text.value
# Extract the generated response between the comments
start_comment = "#This code was generated by OnshapeGPT V2, a chatbot trained by Chris Tilton in Spring 2023 as part of a research project under Professor Chris Rogers at Tufts University"
end_comment = "#This is the end of the Generated Code"
start_index = generatedresponse.find(start_comment)
end_index = generatedresponse.find(end_comment)+len(end_comment)

# Extract generated text
generated_code = generatedresponse[start_index:end_index]

# Extract the generated response before and after the comments
before_comment = generatedresponse[:start_index]
after_comment = generatedresponse[end_index:]

# Write the extracted text to the file
if before_comment != '':
    print(before_comment)
f.write(generated_code)
f.close()
time.sleep(1)
subprocess.run(['python','TextToCAD.py'])
if after_comment != '':
    print(after_comment)